import type { DownloadListItem } from "@/components/downloads/download-list";
import { downloadUrl } from "@/lib/downloads-url";

/** Verbatim from the legacy downloads.html "FORMS" table (commented-out superseded rows dropped). */
export const downloadForms: DownloadListItem[] = [
  { title: "Date of Birth Change / Correction", href: "https://correction.biselahore.com/" },
  { title: "Student Name Change / Correction", href: "https://correction.biselahore.com/" },
  { title: "Student Father Name Change / Correction", href: "https://correction.biselahore.com/" },
  { title: "Name / Father Name / CNIC Correction / Change (according to Matric Record)", href: downloadUrl("/downloads/forms/Form4_CrAccordingMatric.pdf") },
  { title: "Record be changed according to Registration Return", href: downloadUrl("/downloads/forms/RegReturn_Name_Correction.pdf") },
  { title: "Matric / Intermediate Spelling Correction / CNIC Correction / Change", href: downloadUrl("/downloads/forms/Spelling_Change_New.pdf") },
  { title: "Subject Correction / Change", href: downloadUrl("/downloads/forms/Subject_Change_New.pdf") },
  { title: "Migration Form (School to School / College to College)", href: downloadUrl("/downloads/forms/Form_NOC_Institutes.pdf") },
  { title: "College Migration / Change", href: "https://eportal.biselahore.com/eservices" },
  { title: "Board Migration / Change", href: "https://eportal.biselahore.com/eservices" },
  { title: "Application Form for Original Before Time (OBT) Certificate", href: downloadUrl("/downloads/forms/Apl_OBT.pdf") },
  { title: "Duplicate Certificate / Result Card", href: "https://eportal.biselahore.com/eservices" },
  { title: "Degree Attestation Form", href: "https://eportal.biselahore.com/eservices" },
  { title: "Teacher BioData Form (Conduct)", href: downloadUrl("/downloads/forms/Conduct_Duties.pdf") },
  { title: "Marking Duties Form (Secrecy)", href: downloadUrl("/downloads/forms/MarkingDuties2025.pdf") },
  { title: "Institution's Affiliation Extension Form", href: downloadUrl("/downloads/forms/Affil._ExtensionForm.pdf") },
  { title: "Examination Center Availability Form For Matric/Inter (Annual/Supply) & Acceptance of Resident Inspector", href: downloadUrl("/downloads/forms/RI_Acceptance.pdf") },
  { title: "Resident Inspector's Report Form", href: downloadUrl("/downloads/forms/RI_ReportFormNew1703.pdf") },
  { title: "Acceptance / Declaration For Examination Duty", href: downloadUrl("/downloads/forms/Acceptance.pdf") },
  { title: "Centre Visit Report of Distributing Inspector", href: downloadUrl("/downloads/forms/Centre_VisitReport_DI.pdf") },
  { title: "Questionaire for Inspectors of Examination Centres / Mobile Inspectors", href: downloadUrl("/downloads/forms/Quest._ExamDuty.pdf") },
  { title: "Bill for Distributing Inspector", href: downloadUrl("/downloads/forms/Bill_DI2023.pdf") },
  { title: "Bill for Resident Inspector", href: downloadUrl("/downloads/forms/Bill_RI2023.pdf") },
  { title: "Practical Examiner Duty/Acceptance Form", href: downloadUrl("/downloads/forms/Pr_Ex_Acceptance.pdf") },
  { title: "Enrolement / Registration Form (Manual)", href: downloadUrl("/downloads/forms/Manual_RegReturn.pdf") },
  { title: "Proforma for Affiliation", href: downloadUrl("/downloads/careers/Proforma_Affiliation.pdf") },
  { title: "Marking Acceptance Proforma for SSC Annual Examination, 2025", href: downloadUrl("/downloads/forms/MarkingAccept._Proforma.pdf") },
  { title: "Centre Superintendent's File – List of Forms Required for Exam Duty", href: downloadUrl("/downloads/forms/Supdt._File.pdf") },
  { title: "Practical Examiner's File – List of Forms Required for Exam Duty", href: downloadUrl("/downloads/forms/Pr.Examiner_File.pdf") },
  { title: "Guidebook for Supervisory Staff for Theory Examination", href: downloadUrl("/downloads/forms/GuideBook_SupervisoryStaff.pdf") },
  { title: "Guidebook for Practical Examiners", href: downloadUrl("/downloads/forms/GuideBook_Practicals.pdf") },
  { title: "Application Form for use of Office Vehicle (Private) − (for BISE Employees Only)", href: downloadUrl("/downloads/forms/AplForm_Vehicle.pdf") },
  { title: "Application Form for Hijri Scholarship (For Teacher's Child Only)", href: downloadUrl("/downloads/notifications/misc/ScholarshipForm_Hijri.pdf") },
];
