import { downloadUrl } from "@/lib/downloads-url";

export interface NotificationEntry {
  title: string;
  href: string;
}

/** Verbatim from the legacy notifications.html (HTML-commented-out/superseded entries dropped), newest first. */
export const allNotifications: NotificationEntry[] = [
  { title: "Online Registration / Admission Schedule for Intermediate (11th-Class) Academic Session 2026-28", href: downloadUrl("/downloads/notifications/admissions/2026/RegSch_Inter2026_28.pdf") },
  { title: "Admission Schedule SSC (Second Annual) Examination, 2026", href: downloadUrl("/downloads/notifications/admissions/2026/AdmSch_2ndAnn26.pdf") },
  { title: "Private Registration Schedule (9th Class) for First Annual Examination 2027", href: downloadUrl("/downloads/notifications/admissions/Pvt_RegSch(1stA27).pdf") },
  { title: "Private Registration Schedule for Second Annual Examination 2026", href: downloadUrl("/downloads/notifications/admissions/Pvt_RegSch(SA26).pdf") },
  { title: "Revised Registration Schedule for 9th Class Academic Session 2026-2028", href: downloadUrl("/downloads/notifications/admissions/RevRegSch_9th_Regular.pdf") },
  { title: "Booklet Enrollment / Admission (9th Class) Session 2026-2028", href: downloadUrl("/downloads/notifications/misc/9th_Booklet_Reg_Sess2026-28.pdf") },
  { title: "Instructions regarding Practical Examination of SSC (Part-II) (First Annual) Exam, 2026", href: downloadUrl("/downloads/notifications/examination/Instr_Pr.Exam.pdf") },
  { title: "Date Sheet for Intermediate (First Annual) Examination 2026", href: downloadUrl("/downloads/Datesheets/Inter/DS_Inter_1stA26.pdf") },
  { title: "Submission of Admission Forms with Single Fee for Candidates Granted Additional Chances", href: downloadUrl("/downloads/notifications/admissions/AdmLastDate_Add.Chances.pdf") },
  { title: "Date Sheet for SSC (First Annual) Examination 2026", href: downloadUrl("/downloads/Datesheets/Matric/DS_SSC_Ann2026.pdf") },
  { title: "Revised Admission Schedule for Intermediate (First Annual) Examination 2026", href: downloadUrl("/downloads/notifications/admissions/RevAdmInter_1stAnn26.pdf") },
  { title: "Arrangements for Biometric Thumb Impressions for Registration of Class-IX and Class-XI Candidates", href: downloadUrl("/downloads/notifications/misc/Biometric.pdf") },
  { title: "Inter Registration Schedule for Candidates Passing in SSC (Second Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/InterRegSch_forSSC2ndAnn_Students.pdf") },
  { title: "Revised Admission Schedule for SSC (First Annual) Examination 2026", href: downloadUrl("/downloads/notifications/admissions/Rev_AdmSSC_1stAnn2026.pdf") },
  { title: "Syllabus of Class 9th for Hearing Impaired Children (Session 2025-26)", href: downloadUrl("/downloads/notifications/misc/Syllabus9th_HImp.pdf") },
  { title: "Pairing Schemes and Model Papers of Matric-Tech Subjects for Grade-9 (Annual Examination 2026)", href: downloadUrl("/downloads/notifications/misc/PS&MP_MatricTech.pdf") },
  { title: "Inter-Collegiate (Girls) Games Schedule and Entry Form for the Year 2025-2026", href: downloadUrl("/downloads/notifications/misc/InterCollege_GamesGirls.pdf") },
  { title: "Date Sheet for Intermediate (Second Annual) Examination 2025", href: downloadUrl("/downloads/Datesheets/Inter/DS_Inter2ndAnn.pdf") },
  { title: "Re-Admission Schedule for HSSC Part-I (11th Class) Academic Session (2025-2027)", href: downloadUrl("/downloads/notifications/admissions/ReAdmission11th_2025.pdf") },
  { title: "Revised Regular Registration Schedule for Intermediate Class-XI (Session 2025-2027)", href: downloadUrl("/downloads/notifications/admissions/Rev_Reg11th_Regular25_27.pdf") },
  { title: "Date Sheet for SSC (Second Annual) Examination 2025", href: downloadUrl("/downloads/Datesheets/Matric/DS_SSC_2ndAnn25.pdf") },
  { title: "Admission Schedule for Intermediate (Second Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/AdmSch_InterS25.pdf") },
  { title: "Updated Scheme of Studies and Syllabus for HSSC 11th and 12th (Academic Session 2025-2027)", href: downloadUrl("/downloads/notifications/misc/Syllabus_11th&12th_(2025-2027).pdf") },
  { title: "Notification regarding Postponement of SSC (Second Annual) Examination 2025", href: downloadUrl("/downloads/notifications/examination/SSCExams_Postponed.pdf") },
  { title: "Re-Admission Schedule for SSC Part-I (9th Class) Academic Session (2025-2027)", href: downloadUrl("/downloads/notifications/admissions/ReAdm9th_2025_27.pdf") },
  { title: "Private Pre-Registration Schedule for HSSC (First Annual) Examination 2026", href: downloadUrl("/downloads/notifications/admissions/PvtReg_HSSC_1stAnn26.pdf") },
  { title: "Private Pre-Registration Schedule for HSSC (Second Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/PvtReg_HSSC_2ndAnn25.pdf") },
  { title: "Updated Scheme of Studies and Syllabus for SSC 9th and 10th (Academic Session 2025-2027)", href: downloadUrl("/downloads/notifications/misc/Syllabus_9th&10th_(2025_27).pdf") },
  { title: "Gazette Secondary School Certificate (First Annual) Examination 2025", href: "https://drive.google.com/file/d/1RrqD05LHoKs7S3xPCg_Z-BM02Dthiygu/view?usp=sharing" },
  { title: "Admission Schedule for SSC (Second Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/Adm_SSC(2ndAnn)25.pdf") },
  { title: "Notification regarding Scheme of Studies for Humanities Group and Science Group of Matric", href: downloadUrl("/downloads/notifications/misc/SOS_Matric.pdf") },
  { title: "Information regarding Single Textbook of Mathematics for Grade-9 for Science and Humanities Groups for the Academic Session 2025-26", href: downloadUrl("/downloads/notifications/misc/PCTB_MathBook.pdf") },
  { title: "Complete Ban on unauthorized entry into the Matric Tabulation Branches till the declaration of Result", href: downloadUrl("/downloads/notifications/misc/Ban_MatricBranch.pdf") },
  { title: "Private Pre-Enrolment Schedule for SSC (First Annual) Examination 2026", href: downloadUrl("/downloads/notifications/admissions/RegSchSSC2025_Pvt.pdf") },
  { title: "Strict Ban on unauthorized Entry into Marking Centers established by BISE, Lahore", href: downloadUrl("/downloads/notifications/misc/Ban_UnauthorizedEntry.pdf") },
  { title: "Private Pre-Enrolment Schedule for SSC (2nd Annual) Examination 2025 (Composite)", href: downloadUrl("/downloads/notifications/admissions/PvtReg_SSC_2ndAnn25.pdf") },
  { title: "Revised Enrolment Schedule for SSC (9th Class) Academic Session 2025-27 (Regular)", href: downloadUrl("/downloads/notifications/admissions/Rev1_RegSchSSC25_Reg.pdf") },
  { title: "Special Instructions for the smooth and transparent conduct of Examinations and Practicals 2025 onwards", href: downloadUrl("/downloads/notifications/examination/Exams_Instructions.pdf") },
  { title: "Revised Schedule for Postponed Papers of SSC (Practical) & HSSC (Theory) First Annual Examination 2025", href: downloadUrl("/downloads/notifications/examination/ReschedulingofPapers.pdf") },
  { title: "Booklet Enrolment / Admission 9th Class (Session 2025-27)", href: downloadUrl("/downloads/notifications/misc/9thBooklet_Reg2025_27.pdf") },
  { title: "Resumption of HSSC Theory and SSC Practical Exams on May 12, 2025 onward", href: downloadUrl("/downloads/notifications/examination/ResumptionofExamsMONDAY.pdf") },
  { title: "Postponement of Intermediate Theory and Matric Practical Papers dated May 09, 2025 (Friday)", href: downloadUrl("/downloads/notifications/examination/PapersPostponed080525.pdf") },
  { title: "Scheme of Studies for the Groups of Matric-Tech", href: downloadUrl("/downloads/notifications/misc/New_Sch.ofStudies_MatricTech.pdf") },
  { title: "Resumption of HSSC Theory and SSC Practical Exams on May 08, 2025 onward", href: downloadUrl("/downloads/notifications/examination/ResumptionofExams.pdf") },
  { title: "New Groups in Matric Scheme of Studies Academic Session (2025-27)", href: downloadUrl("/downloads/notifications/admissions/NewGroupsMatric.pdf") },
  { title: "Postponement of Intermediate Theory and Matric Practical Papers dated May 07, 2025", href: downloadUrl("/downloads/notifications/examination/Papers_Postponed070525.pdf") },
  { title: "Attraction of the Young Generation on key and multifarious aspects from the Life of Rehmatul-lil-Aalameen", href: downloadUrl("/downloads/notifications/misc/Notification_IBCC.pdf") },
  { title: "Special Instructions regarding Practical Examinations SSC & HSSC 1st Annual Examinations 2025", href: downloadUrl("/downloads/notifications/examination/Special_Instructions_PracticalsEx.pdf") },
  { title: "Notification for all Supervisory Staff, Marking Staff and other Officers / Officials engaged in conduct of SSC / HSSC Examinations 2025", href: downloadUrl("/downloads/notifications/examination/Notification_AllDuties.pdf") },
  { title: "Poor response regarding availability of Human Resource for Conduct of upcoming Annual Examinations 2025", href: downloadUrl("/downloads/notifications/examination/PoorResponse.pdf") },
  { title: "Enrolment Schedule for SSC (9th Class) Academic Session 2025-27 (Regular)", href: downloadUrl("/downloads/notifications/admissions/RegSchSSC25_Regular.pdf") },
  { title: "Date Sheet for Intermediate Part-I & II (First Annual) Examination 2025", href: downloadUrl("/downloads/Datesheets/Inter/DS_Inter_1stA25.pdf") },
  { title: "Directions for Practical Examiners for SSC and HSSC Examinations 2025 and onwards for all Examinations", href: downloadUrl("/downloads/notifications/examination/Directions_Pr.Examiners.pdf") },
  { title: "Reiteration of already issued Instructions regarding Registration of UMC, Impersonation Cases, FIRs & Stray Cases", href: downloadUrl("/downloads/notifications/examination/UMC_Impersonation.pdf") },
  { title: "International Science Olympiads - by STEM Career Programme", href: downloadUrl("/downloads/notices/STEM_ScienceOlymp25.pdf") },
  { title: "Strict Ban on uploading & sharing of Guess Papers, Pairing Scheme & BISE old / previous Question Papers on Social Media", href: downloadUrl("/downloads/notifications/misc/Strict_Ban.pdf") },
  { title: "2nd International Mathematics Olympiad for School Students Scheduled to be Organized on 21-26 April, 2025 at Ashgabat, Turkmenistan", href: downloadUrl("/downloads/notifications/misc/Math_Olympiad.pdf") },
  { title: "Special and Emergent Instructions regarding Marking of SSC Examination 2025 and All Examinations", href: downloadUrl("/downloads/notifications/examination/Instructions_Marking.pdf") },
  { title: "Requestion for Extension of Protection to BISE Materials Present in the Centers", href: downloadUrl("/downloads/notifications/examination/BISE_Material.pdf") },
  { title: "Strict action against external elements tending to exert pressure & influence for helping the candidates in the Examination", href: downloadUrl("/downloads/notifications/examination/External_Infl.pdf") },
  { title: "Instruction regarding Registration & Making of Impersonation, UMC & Stray Cases in the Examinations", href: downloadUrl("/downloads/notifications/examination/Reg_UMCs.pdf") },
  { title: "Directions for Resident Inspectors regarding Smooth Conduct of SSC (First Annual) Examination 2025", href: downloadUrl("/downloads/notifications/examination/RIs_Interference.pdf") },
  { title: "Special and Emergent Instructions regarding Conduct of SSC Exam 2025", href: downloadUrl("/downloads/notifications/examination/Special_InstructionsSSC25.pdf") },
  { title: "Failure to attend Official's Calls", href: downloadUrl("/downloads/notifications/examination/FailuretoAttendCalls.pdf") },
  { title: "Strict Compliance of the Assigned Supervisory Duties by the BISE, Lahore for SSC (First Annual) Examination, 2025", href: downloadUrl("/downloads/notifications/examination/NoRefusal.pdf") },
  { title: "Registration of Students of Grade-IX to Grade-XII for Participating in Pakistan Olympiad in Informatics (POI) Contest 2025", href: downloadUrl("/downloads/notifications/misc/POI_Contest2025.pdf") },
  { title: "Measures for SSC / HSSC (1st Annual) Examination, 2025", href: downloadUrl("/downloads/notifications/examination/Letter_ExamMeasures.pdf") },
  { title: "Date Sheet for SSC (First Annual) Examination 2025", href: downloadUrl("/downloads/Datesheets/Matric/DS_Matric_1stA25.pdf") },
  { title: "Letter for Formulating SOPs to Prevent Risky Situations", href: downloadUrl("/downloads/notifications/misc/SOPs_PreventRisk.pdf") },
  { title: "Availability of Necessary Practical Equipment in the Laboratory for Practical Examinations", href: downloadUrl("/downloads/notifications/examination/Practical_Equipment.pdf") },
  { title: "Notification regarding dissemination / sharing of Question Papers", href: downloadUrl("/downloads/notifications/misc/Notification_SharingPprs.pdf") },
  { title: "Admission Schedule for Intermediate (First Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/AdmSch_Inter1stA25.pdf") },
  { title: "Extension in Admission Schedule for SSC (First Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/Ext_AdmSCC25.pdf") },
  { title: "SSC Enrolment / Registration Schedule (Regular) Under Amended Age Limits", href: downloadUrl("/downloads/notifications/admissions/Rev_RegEnrSch_SSC_1.pdf") },
  { title: "SSC Enrolment / Registration Schedule (Private) Under Amended Age Limits", href: downloadUrl("/downloads/notifications/admissions/Rev_PvtEnrSch_SSC.pdf") },
  { title: "Amended Rule for Minimum Age Limit for 9th Class Registration", href: downloadUrl("/downloads/notifications/misc/Notification_MinAgeLimit.pdf") },
  { title: "Clarification regarding Implementation of Updated Syllabus of 9th & 10th Classes", href: downloadUrl("/downloads/notifications/misc/Clarification_Syllabus.pdf") },
  { title: "Rescheduling of Intermediate (Second Annual) 2024 Postponed Papers", href: downloadUrl("/downloads/notifications/examination/Papers_Rescheduled.pdf") },
  { title: "Admission Schedule SSC (First Annual) Examination 2025", href: downloadUrl("/downloads/notifications/admissions/AdmSch_SSC1stA25.pdf") },
  { title: "Date Sheet Intermediate (Second Annual) Examination 2024", href: downloadUrl("/downloads/Datesheets/Inter/DS_Inter_2ndA24.pdf") },
  { title: "Re-Admission Schedule for HSSC (11th Class) Academic Session 2024-26", href: downloadUrl("/downloads/notifications/admissions/ReAdmission_Inter24.pdf") },
  { title: "Revised Regular Registration Schedule for Intermediate (Session 2024-26)", href: downloadUrl("/downloads/notifications/admissions/RevRegInter25_Reg.pdf") },
  { title: "Directions for Practical Examiners for Matric and Intermediate Examinations and Onwards for All Examinations (SSC & HSSC)", href: downloadUrl("/downloads/notifications/examination/Directions_PrExaminers.pdf") },
  { title: "Admission Schedule Intermediate (Second Annual) Examination 2024", href: downloadUrl("/downloads/notifications/admissions/AdmSch_Inter2ndAnn24.pdf") },
  { title: "Notification Regarding Certificates before 2022 as OBT", href: downloadUrl("/downloads/notifications/Notification%20Regarding%20Certificates%20before%202022%20as%20OBT.jpeg") },
  { title: "Re-Admission Schedule for SSC (9th Class) Academic Session 2024-26", href: downloadUrl("/downloads/notifications/admissions/ReAdm_SSC24.pdf") },
  { title: "Date Sheet for SSC (Second Annual) Examination 2024", href: downloadUrl("/downloads/Datesheets/Matric/DS_SSC_2ndA2024.pdf") },
  { title: "Gazette SSC (First Annual) Examination, 2024", href: downloadUrl("/downloads/notifications/misc/2024%2010th.pdf") },
  { title: "Admission Schedule for SSC (Second Annual) Examination, 2024", href: downloadUrl("/downloads/notifications/admissions/AdmSch_SSC_2ndA24.pdf") },
  { title: "Notification regarding Islamiat in 9th and Pak Studies in 10th Class", href: downloadUrl("/downloads/notifications/misc/Isl9th_Pst10th.pdf") },
  { title: "Temporary Opening of Portal before Re-Inspection", href: downloadUrl("/downloads/notifications/misc/Portal_Opening.jpg") },
  { title: "Failure to attend Official Calls from BISE", href: downloadUrl("/downloads/notifications/misc/FAILURE%20TO%20ATTEND%20OFFICIAL%20CALLS%20FROM%20BISE%20.pdf") },
  { title: "Provision of Halls for BISE Examination", href: downloadUrl("/downloads/notifications/misc/PROVISION%20OF%20HALLS%20FOR%20BISE%20EXAMS.pdf") },
  { title: "Enrolment Schedule for SSC (9th Class) Academic Session 2024-26", href: downloadUrl("/downloads/notifications/admissions/RegSSC24.pdf") },
  { title: "Date Sheet for Intermediate (First Annual) Examination 2024", href: downloadUrl("/downloads/Datesheets/Inter/DS_Inter1stA2024.pdf") },
  { title: "Date Sheet for SSC (First Annual) Examination 2024", href: downloadUrl("/downloads/Datesheets/Matric/DS_SSC_1stA2024.pdf") },
  { title: "Notification regarding Tarjuma-tul-Quran Subject for Deaf and Dumb Candidates", href: downloadUrl("/downloads/notifications/misc/Noti_TQuran_DD.pdf") },
  { title: "Amended Passing Criteria in Theory & Practical Subjects", href: downloadUrl("/downloads/notifications/examination/NewPassingCriteria.pdf") },
  { title: "Amended Policy regarding Marks Improvement", href: downloadUrl("/downloads/notifications/misc/Policy_MarksImprv24.pdf") },
  { title: "Notification regarding revised remuneration for Invigilators", href: downloadUrl("/downloads/notifications/misc/RevisedRemInvig.pdf") },
  { title: "Notification regarding unbundling of Scheme of Studies from the Academic Session 2022-23", href: downloadUrl("/downloads/notifications/misc/Notification_Scheme2111.pdf") },
  { title: "Notification regarding Textbook of Mutala-e-Pakistan / Pakistan Studies Grade-12", href: downloadUrl("/downloads/notifications/misc/PSt_12th_PCTB.pdf") },
  { title: "Books of \"Imraniyat (Sociology) Part-I & II\" for Intermediate Level Written by Muhammad Kashif is banned for Teaching", href: downloadUrl("/downloads/notifications/misc/Book_Sociology.pdf") },
  { title: "Instruction regarding the use of PNB Computer Science for Grade-X for Academic Session 2021-22", href: downloadUrl("/downloads/notices/PNB_CS.pdf") },
  { title: "New Syllabus of Geography for Intermediate (Part-I & II)", href: downloadUrl("/downloads/notifications/Syllabus_Geo.pdf") },
  { title: "Notification Regarding Practical Examination for the Subject of Computer Science SSC (Part-II)", href: downloadUrl("/downloads/notifications/Pr_Exam_CS.pdf") },
  { title: "Notification regarding Local Migration at HSSC Level", href: downloadUrl("/downloads/notifications/CollegeMigr.pdf") },
];
