import type { DownloadListItem } from "@/components/downloads/download-list";

/** Verbatim from the legacy tenders.html (25 entries). */
export const tenderNotices: DownloadListItem[] = [
  { title: "Tender Notice for the procurement of UPS and Network Switches", href: "/downloads/tenders/Tender_UpsNetwork.pdf" },
  { title: "Tender Notice for the procurement of Printers", href: "/downloads/tenders/Tender_Printers2502.pdf" },
  { title: "Tender Notice for the procurement of Computers and Laptops", href: "/downloads/tenders/Tender_PC_Laptops.pdf" },
  { title: "Tender Notice for the procurement of Heavy Duty Printers", href: "/downloads/tenders/Tender_HDutyPrinter.pdf" },
  { title: "Tender Notice for the sale of Waste Paper (Raddi)", href: "/downloads/tenders/Tender_Raddi0226.pdf" },
  { title: "Tender Notice for the Framework Contract for hiring the Security Services / Security Guards", href: "/downloads/tenders/Tender_SGuards1225.pdf" },
  { title: "Tender Notice for the Framework contract for hiring the Examination Furniture etc.", href: "/downloads/tenders/Tender_ExamsFurniture.pdf" },
  { title: "Tender Notice for the procurement of HP Toners / Catridges for different model of Printers", href: "/downloads/tenders/Tender_Toners0411.pdf" },
  { title: "Tender Notice for the procurement of White Printing / Writing Paper Ruled (Lined)", href: "/downloads/tenders/Tender_WhitePaper.pdf" },
  { title: "Tender Notice for the procurement of Polythene Envelopes and Polythene Shopping Bags", href: "/downloads/tenders/Tender_Bags0411.pdf" },
  { title: "Tender Notice for the Framework Contract for SMS Services", href: "/downloads/tenders/Tender_SMSService.pdf" },
  { title: "Tender Notice for the procurement of Drums, Kits, Ink Catridges & Accessories", href: "/downloads/tenders/Tender_PrintersInks.pdf" },
  { title: "Tender Notice for the procurement of Offset Paper Imported", href: "/downloads/tenders/Tender_OffsetPaperImported.pdf" },
  { title: "Tender Notice for the procurement of Biodegradable Envelopes", href: "/downloads/tenders/Tender_BDEnvelops.pdf" },
  { title: "Tender Notice for the preparation of Answer Sheets", href: "/downloads/tenders/Tender_AnswerSheets0411.pdf" },
  { title: "Tender Notice for the procurement of Offset Paper Imported Size A3", href: "/downloads/tenders/Tender_OffsetPaper0411.pdf" },
  { title: "Tender Notice for the procurement of Cloth Bags", href: "/downloads/tenders/Tender_ClothBag0411.pdf" },
  { title: "Tender Notice for the procurement of Craft Paper, Scholar Paper & Drawing Paper", href: "/downloads/tenders/Tender_CraftPaper.pdf" },
  { title: "Tender Notice for the procurement of Cover Sheets", href: "/downloads/tenders/Tender_Coversheets0411.pdf" },
  { title: "Tender Notice for the procurement of Sports Items / Goods / Material for the Sports Competitions", href: "/downloads/tenders/Tender_Kits.pdf" },
  { title: "Tender Notice for the procurement of Inks for Copyprinters and Master Rolls etc.", href: "/downloads/tenders/Tender_BlackInk.pdf" },
  { title: "Tender Notice for the Framework Contract regarding hiring of vehicles", href: "/downloads/tenders/Tender_Vehicles0411.pdf" },
  { title: "Tender Notice for the Framework Contract regarding hiring of Examination Furniture / Items etc.", href: "/downloads/tenders/Tender_MiscItems0411.pdf" },
  { title: "Tender Notice for the procurement of Items (Printing Inks, Thread Cones, Glue etc.)", href: "/downloads/tenders/Tender_PrintingItems.pdf" },
  { title: "Tender Notice for the procurement of Stationery Items / Goods / Materials.", href: "/downloads/tenders/Tender_Stationery2410.pdf" },
];
